/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.student;
import java.util.Scanner;
import org.stud.reg.UseCase.AdminMenu;
import org.stud.reg.UseCase.FacultyMenu;
import org.stud.reg.UseCase.StudentMenu;
import org.stud.reg.bean.Faculty;

public class App {
    public String getStarted() {
        return "WELCOME TO ACADEMIC PORTAL!\n\n";
    }

    static Scanner sc = new Scanner(System.in);
	
	public static void studentAuth() {
		
		System.out.println("PLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		System.out.println("1. Student Login");
		System.out.println("\n\n");
		System.out.println("0. Go Back");
		System.out.println("99. Exit The Application");
		
		try {
			String op = sc.nextLine();
			int option = Integer.parseInt(op);
			StudentMenu student = new StudentMenu();
			
			switch(option){
				case 0 : menu();
					break;
				case 1 : String check = student.login();
				System.out.println("----------------------------------------");
					if(check != "") studentActivity(check);
					else studentAuth();
					break;
				case 99 :
					System.out.println("Thank you for using Application");
					break;
				default : 
					System.out.println("Invalid Selection ");
					System.out.println("----------------------------------------");
					studentAuth();
			}
			
		}catch(Exception e) {
			
			System.out.println("Invalid Selection !");
			System.out.println("----------------------------------------");
			menu();
		}

	}

    public static void studentActivity(String roll) {
		
		System.out.println("\nPLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		System.out.println("1. Show Courses offered for enrolment ");
		System.out.println("2. Register a Course ");
		System.out.println("3. Student Record ");
		System.out.println("\n\n");
		System.out.println("0. Log Out");
		System.out.println("99. Exit the Application");
		
		try {
		
			String op = sc.nextLine();
			int option = Integer.parseInt(op);	
			
			StudentMenu student = new StudentMenu();
			
			switch(option) {
				case 0 : studentAuth();
					break;
				case 1 : //student.updateDetail(roll);
				System.out.println("Courses offered for enrolment ");
				student.showAllCourse();

				System.out.println("----------------------------------------");
					studentActivity(roll);
					break;
				case 2: System.out.println("Register a course");
					student.registerCourse(roll);
					studentActivity(roll);
					break;
				case 3: 
					System.out.println("Student Record");
					student.StudentRecord(roll);
					studentActivity(roll);
					break;
				case 99 :
					System.out.println("Thank you for using Application");
					break;
				default : 
					System.out.println("Invalid Selection ");
					System.out.println("----------------------------------------");
					studentActivity(roll);
			}
		}catch(Exception e) {
			System.out.println("Invalid Selection !");
			System.out.println("----------------------------------------");
			menu();
		}
	}
	
	public static void facultyAuth() {
		System.out.println("PLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		System.out.println("1. Faculty Login");
		System.out.println("\n\n");
		System.out.println("0. Go Back");
		System.out.println("99. Exit The Application");

		FacultyMenu am = new FacultyMenu();
		
		try {
			String op = sc.nextLine();
			int option = Integer.parseInt(op);	
			switch(option) {
			case 0: menu();
				break;
			case 1: int check = am.login();
				if(check == 1) {
					facultyActivity();
				}
				else facultyAuth();
				break;
			case 99 :
				System.out.println("Thank you for using Application");
				break;
			default : 
				System.out.println("Invalid Selection ");
				adminAuth();
			}
			
		}catch(Exception e) {
			System.out.println("Invalid Selection !");
			System.out.println("----------------------------------------");
			adminAuth();
		}

	}

	public static void facultyActivity() {

		System.out.println("PLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		
		System.out.println("1. Add new Course");
		System.out.println("2. Delete Course");
		System.out.println("3. View All Student List");
		System.out.println("4. View All Course List");
		System.out.println("5. Update Grades of students");
		System.out.println("6. Enrollment Requests");
		System.out.println("\n\n");
		System.out.println("0. Log Out");
		System.out.println("99. Exit The Application");

		FacultyMenu fm = new FacultyMenu();
		try {
			
			String op = sc.nextLine();
			int option = Integer.parseInt(op);	
			switch(option) {
				case 0 : 
				// Go back
					adminAuth();
					break;
				case 1 : 
				// Add new courses
					fm.addCourse();
					facultyActivity();
					break;
				case 2:
				// Delete the course
					fm.deleteCourse();
					facultyActivity();
					break;
				case 3:
				// View All Student in batch
					fm.studentList(); 
					facultyActivity(); 
					break;
				case 4:
				// Show All Courses 
					fm.showCourse(); 
					facultyActivity(); 
					break;
				case 5:
				// Show All Courses 
					fm.UpdateGrades(); 
					facultyActivity(); 
					break;
				case 6:
				// Show All Courses 
					System.out.println();
					fm.enrollmentReq(); 
					facultyActivity(); 
					break;
				case 99:
				// Exit From App
					System.out.println("Thank you for using Application");
					break;
				default:System.out.println("Invalid Selection !");
					facultyActivity();
			}

		}catch(Exception e) {
			System.out.println("Invalid Exception");
			System.out.println("----------------------------------------");
			facultyActivity();
		}
	}

	public static void adminAuth() {
		
		System.out.println("PLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		System.out.println("1. Admin Login");
		System.out.println("\n\n");
		System.out.println("0. Go Back");
		System.out.println("99. Exit The Application");
		
		AdminMenu am = new AdminMenu();
		
		try {
			String op = sc.nextLine();
			int option = Integer.parseInt(op);	
			switch(option) {
			case 0: menu();
				break;
			case 1: int check = am.login();
				if(check == 1) adminActivity();
				else adminAuth();
				break;
			case 99 :
				System.out.println("Thank you for using Application");
				break;
			default : 
				System.out.println("Invalid Selection ");
				adminAuth();
			}
			
		}catch(Exception e) {
			System.out.println("Invalid Selection !");
			System.out.println("----------------------------------------");
			adminAuth();
		}
	}

	public static void adminActivity() {
		
		System.out.println("PLEASE SELECT FROM THE FOLLOWING OPTIONS ");
		
		System.out.println("1. Add new Course");
		System.out.println("2. Delete Course");
		System.out.println("3. Add Student in Batch");
		System.out.println("4. View All Student List");
		System.out.println("5. View All Course List");
		System.out.println("6. Generate transcrip of students");
		System.out.println("\n\n");
		System.out.println("0. Log Out");
		System.out.println("99. Exit The Application");
		
		AdminMenu am = new AdminMenu();
		try {
			
			String op = sc.nextLine();
			int option = Integer.parseInt(op);	
			switch(option) {
				case 0 : 
				// Go back
					adminAuth();
					break;
				case 1 : 
				// Add new courses
					am.addCourse();
					adminActivity();
					break;
				case 2:
				// Delete the course
					am.deleteCourse();
					adminActivity();
					break;
				case 3:
				// Add Student to Batch
					am.addStudentToBatch(); 
					adminActivity(); 
				case 4:
				// View All Student in batch
					am.studentList(); 
					adminActivity(); 
					break;
				case 5:
				// Show All Courses 
					am.showCourse(); 
					adminActivity(); 
					break;
				case 6:
				// Show All Courses 
					am.GenerateTranscript(); 
					adminActivity(); 
					break;
				case 99:
				// Exit From App
					System.out.println("Thank you for using Application");
					break;
				default:System.out.println("Invalid Selection !");
					adminActivity();
			}
			
			
		}catch(Exception e) {
			System.out.println("Invalid Exception");
			System.out.println("----------------------------------------");
			adminActivity();
		}
		
	}

	public static void menu() {
		
		System.out.println("PLEASE SELECT FROM THE OPTIONS ");
		System.out.println("1. Student ");
		System.out.println("2. Admin ");
		System.out.println("3. Faculty ");
		System.out.println("\n\n");
		System.out.println("99. Exit the Application");
		
		String op = "";
		int option = 0;
		try {
			op = sc.nextLine();
			option = Integer.parseInt(op);
		} catch (Exception e) {
			// TODO: handle exception
		}
			
	
		if(option == 1) {
			System.out.println("----------------------------------------");
			studentAuth();
		}else if (option==3){
			System.out.println("----------------------------------------");
			facultyAuth();
			System.out.println("Faculty: PLEASE SELECT FROM THE OPTIONS ");
		}else if(option == 2) {
			System.out.println("----------------------------------------");
			adminAuth();
		}
		else if(option == 99) {
			System.out.println("Thank You for using Application.");
		}else {
			System.out.println("Invalid Selection : Please try again");
			menu();
		}
		
	}

    public static void main(String[] args) {
        System.out.println(new App().getStarted());

        // DbFunctions db = new DbFunctions();
        // db.connect_to_db("mydatabase", "sahdev", "Sahdev1115");

		System.out.println("--------------------------------------");
		menu();
		
    }
}